export const POSTS_CREATE = 'posts.POSTS_CREATE'
export const POSTS_UPDATE = 'posts.POSTS_UPDATE'
export const POSTS_DELETE = 'posts.POSTS_DELETE'
export const POSTS_UPVOTE = 'posts.POSTS_UPVOTE'
export const POSTS_DOWNVOTE = 'posts.POSTS_DOWNVOTE'
export const POSTS_FETCHED = 'posts.POSTS_FETCHED'
export const POSTS_FETCHED_BY_CATEGORY = 'posts.POSTS_FETCHED_BY_CATEGORY'
